controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - mara1_motor1
      - mara1_motor2
      - mara1_motor3
      - mara1_motor4
      - mara1_motor5
      - mara1_motor6
      - mara2_motor1
      - mara2_motor2
      - mara2_motor3
      - mara2_motor4
      - mara2_motor5
      - mara2_motor6
