motors:
  - /hrim_actuation_servomotor_000000000001/trajectory_axis2
  - /hrim_actuation_servomotor_000000000001/trajectory_axis1
  - /hrim_actuation_servomotor_000000000002/trajectory_axis1
  - /hrim_actuation_servomotor_000000000002/trajectory_axis2
  - /hrim_actuation_servomotor_000000000003/trajectory_axis1
  - /hrim_actuation_servomotor_000000000003/trajectory_axis2
